apiVersion: v1
kind: Service
metadata:
  name: tss-backend
  namespace: tss-training
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: tss-backend-local
  namespace: tss-training
  labels:
    kubernetes.io/service-name: tss-backend
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 8080
endpoints:
  - addresses:
      - "__HOST_GATEWAY__"
---
apiVersion: v1
kind: Service
metadata:
  name: tss-minio
  namespace: tss-training
spec:
  ports:
    - name: api
      port: 9000
      targetPort: 9010
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: tss-minio-local
  namespace: tss-training
  labels:
    kubernetes.io/service-name: tss-minio
addressType: IPv4
ports:
  - name: api
    protocol: TCP
    port: 9010
endpoints:
  - addresses:
      - "__HOST_GATEWAY__"
---
apiVersion: v1
kind: Service
metadata:
  name: tss-mlflow
  namespace: tss-training
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: tss-mlflow-local
  namespace: tss-training
  labels:
    kubernetes.io/service-name: tss-mlflow
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 5000
endpoints:
  - addresses:
      - "__HOST_GATEWAY__"
