package com.tss.platform.controller;

import com.tss.platform.dto.ApiResponse;
import com.tss.platform.entity.DatasetAsset;
import com.tss.platform.entity.DatasetVersion;
import com.tss.platform.repository.DatasetAssetRepository;
import com.tss.platform.repository.DatasetVersionRepository;
import com.tss.platform.repository.TrainingExperimentVersionRepository;
import com.tss.platform.security.AuthContext;
import com.tss.platform.service.MinioDeleteTaskService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import java.time.Instant;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/api/dataset-versions")
public class DatasetVersionCrudController {

    private static final Logger log = LoggerFactory.getLogger(DatasetVersionCrudController.class);
    private static final String STATUS_DRAFT = "DRAFT";
    private static final String STATUS_READY = "READY";
    private static final String STATUS_DEPRECATED = "DEPRECATED";
    private static final String STATUS_ARCHIVED = "ARCHIVED";

    private final DatasetVersionRepository repo;
    private final DatasetAssetRepository assetRepo;
    private final TrainingExperimentVersionRepository trainingRepo;
    private final MinioDeleteTaskService minioDeleteTaskService;
    private final AuthContext authContext;

    public DatasetVersionCrudController(
            DatasetVersionRepository repo,
            DatasetAssetRepository assetRepo,
            TrainingExperimentVersionRepository trainingRepo,
            MinioDeleteTaskService minioDeleteTaskService,
            AuthContext authContext
    ) {
        this.repo = repo;
        this.assetRepo = assetRepo;
        this.trainingRepo = trainingRepo;
        this.minioDeleteTaskService = minioDeleteTaskService;
        this.authContext = authContext;
    }

    @PostMapping
    @Transactional
    public ApiResponse<DatasetVersion> create(@RequestBody DatasetVersion body) {
        if (body.getAssetId() == null || body.getAssetId().isBlank()) {
            return ApiResponse.fail("assetId cannot be empty");
        }
        body.setAssetId(body.getAssetId().trim());
        body.setId("dataset-ver-" + UUID.randomUUID().toString().replace("-", ""));
        Optional<DatasetAsset> asset = assetRepo.findByIdAndDeletedFalseForUpdate(body.getAssetId());
        if (asset.isEmpty()) {
            return ApiResponse.fail("dataset asset not found: " + body.getAssetId());
        }
        Integer ownerUserId = asset.get().getOwnerUserId();
        if (!authContext.canAccessOwner(ownerUserId)) {
            return ApiResponse.fail("no permission for asset: " + body.getAssetId());
        }
        if (!authContext.isAdmin()) {
            return ApiResponse.fail("dataset versions must be created by upload service");
        }
        if (hasStorageMetadata(body)) {
            return ApiResponse.fail("storage metadata can only be generated by upload service");
        }
        Integer maxVersionNo = repo.findMaxVersionNoByAssetId(body.getAssetId());
        int nextVersionNo = (maxVersionNo == null ? 0 : maxVersionNo) + 1;
        String targetLabel = versionLabel(body);
        if (targetLabel == null) {
            targetLabel = "v" + nextVersionNo;
        }
        body.setVersion(targetLabel);
        body.setVersionLabel(targetLabel);
        if (repo.existsByAssetIdAndVersion(body.getAssetId(), targetLabel)) {
            return ApiResponse.fail("dataset version already exists for asset: " + body.getAssetId());
        }
        body.setVersionNo(nextVersionNo);
        String targetStatus;
        try {
            targetStatus = body.getStatus() == null || body.getStatus().isBlank()
                    ? STATUS_DRAFT
                    : normalizeVersionStatus(body.getStatus());
        } catch (IllegalArgumentException e) {
            return ApiResponse.fail(e.getMessage());
        }
        if (!STATUS_DRAFT.equals(targetStatus)) {
            return ApiResponse.fail("manual dataset version creation only supports DRAFT");
        }
        Optional<DatasetVersion> activeDraft =
                repo.findTopByAssetIdAndDeletedFalseAndStatusOrderByVersionNoDesc(
                        body.getAssetId(),
                        STATUS_DRAFT
                );
        if (activeDraft.isPresent()) {
            return ApiResponse.fail(activeDraftMessage(activeDraft.get()));
        }
        body.setStatus(targetStatus);
        body.setOwnerUserId(ownerUserId != null ? ownerUserId : authContext.currentUserId());
        body.setCreatedBy(authContext.currentUserId());
        if (body.getCreatedAt() == null) {
            body.setCreatedAt(Instant.now());
        }
        if (STATUS_READY.equals(body.getStatus()) && body.getPublishedAt() == null) {
            body.setPublishedAt(body.getCreatedAt());
        }
        body.setDeleted(false);
        body.setDeletedAt(null);
        try {
            return ApiResponse.ok(repo.saveAndFlush(body));
        } catch (DataIntegrityViolationException e) {
            if (isOneActiveDraftViolation(e)) {
                return ApiResponse.fail("dataset asset already has an active DRAFT version");
            }
            throw e;
        }
    }

    @GetMapping("/{id}")
    public ApiResponse<DatasetVersion> get(@PathVariable String id) {
        Optional<DatasetVersion> v = repo.findByIdAndDeletedFalse(id);
        if (v.isEmpty() || !authContext.canAccessOwner(effectiveOwner(v.get()))) {
            return ApiResponse.fail("not found or no permission: " + id);
        }
        return ApiResponse.ok(v.get());
    }

    @GetMapping
    public ApiResponse<List<DatasetVersion>> list(@RequestParam(value = "assetId", required = false) String assetId) {
        if (assetId != null && !assetId.isBlank()) {
            if (authContext.isAdmin()) {
                return ApiResponse.ok(repo.findByAssetIdAndDeletedFalseOrderByVersionNoDesc(assetId));
            }
            if (!authContext.canAccessOwner(resolveAssetOwner(assetId))) {
                return ApiResponse.fail("not found or no permission: " + assetId);
            }
            return ApiResponse.ok(repo.findByAssetIdAndDeletedFalseOrderByVersionNoDesc(assetId));
        }
        if (authContext.isAdmin()) {
            return ApiResponse.ok(repo.findByDeletedFalse());
        }
        Set<String> assetIds = assetRepo.findByOwnerUserIdAndDeletedFalse(authContext.currentUserId())
                .stream()
                .map(DatasetAsset::getId)
                .filter(id -> id != null && !id.isBlank())
                .collect(Collectors.toSet());
        return ApiResponse.ok(assetIds.isEmpty() ? List.of() : repo.findByAssetIdInAndDeletedFalse(assetIds));
    }

    @PutMapping("/{id}")
    public ApiResponse<DatasetVersion> update(@PathVariable String id, @RequestBody DatasetVersion body) {
        Optional<DatasetVersion> existing = repo.findByIdAndDeletedFalse(id);
        if (existing.isEmpty()) {
            return ApiResponse.fail("未找到: " + id);
        }
        DatasetVersion e = existing.get();
        if (!authContext.canAccessOwner(effectiveOwner(e))) {
            return ApiResponse.fail("no permission: " + id);
        }
        String targetAssetId = body.getAssetId() == null || body.getAssetId().isBlank()
                ? e.getAssetId()
                : body.getAssetId().trim();
        String targetVersion = versionLabel(body);
        if (targetVersion == null) {
            return ApiResponse.fail("version cannot be empty");
        }
        if (!Objects.equals(targetAssetId, e.getAssetId())) {
            return ApiResponse.fail("assetId cannot be modified");
        }
        if (storageMetadataChanged(e, body)) {
            return ApiResponse.fail("storage metadata cannot be modified");
        }
        Integer ownerUserId = resolveAssetOwner(targetAssetId);
        if (!authContext.canAccessOwner(ownerUserId)) {
            return ApiResponse.fail("no permission for asset: " + targetAssetId);
        }
        if (repo.existsByAssetIdAndVersionAndIdNot(targetAssetId, targetVersion, id)) {
            return ApiResponse.fail("dataset version already exists for asset: " + targetAssetId);
        }
        e.setAssetId(targetAssetId);
        e.setVersion(targetVersion);
        e.setVersionLabel(targetVersion);
        e.setRemark(body.getRemark());
        e.setDescription(body.getDescription());
        e.setChangeLog(body.getChangeLog());
        e.setOwnerUserId(ownerUserId != null ? ownerUserId : e.getOwnerUserId());
        return ApiResponse.ok(repo.save(e));
    }

    @PatchMapping("/{id}/status")
    public ApiResponse<DatasetVersion> updateStatus(
            @PathVariable String id,
            @RequestBody Map<String, String> body
    ) {
        Optional<DatasetVersion> existing = repo.findByIdAndDeletedFalse(id);
        if (existing.isEmpty() || !authContext.canAccessOwner(effectiveOwner(existing.get()))) {
            return ApiResponse.fail("not found or no permission: " + id);
        }
        DatasetVersion version = existing.get();
        DatasetAsset asset = assetRepo.findByIdAndDeletedFalse(version.getAssetId()).orElse(null);
        if (asset == null) {
            return ApiResponse.fail("dataset version parent asset not found or deleted: " + version.getAssetId());
        }
        String status = body == null ? null : body.get("status");
        String targetStatus;
        try {
            targetStatus = normalizeStatusTransition(status);
        } catch (IllegalArgumentException e) {
            return ApiResponse.fail(e.getMessage());
        }
        if (STATUS_READY.equals(targetStatus) && isWorkspaceDraft(version)) {
            return ApiResponse.fail("workspace draft publishing is not implemented");
        }
        if (STATUS_READY.equals(targetStatus) && !hasCompleteStorageMetadata(version)) {
            return ApiResponse.fail("READY dataset version requires storage metadata");
        }
        if ((STATUS_DEPRECATED.equals(targetStatus) || STATUS_ARCHIVED.equals(targetStatus))
                && id.equals(asset.getCurrentVersionId())) {
            return ApiResponse.fail("current version cannot be deprecated or archived");
        }
        version.setStatus(targetStatus);
        if (STATUS_READY.equals(targetStatus) && version.getPublishedAt() == null) {
            version.setPublishedAt(Instant.now());
        }
        return ApiResponse.ok(repo.save(version));
    }

    @DeleteMapping("/{id}")
    @Transactional
    public ApiResponse<Map<String, Object>> delete(@PathVariable String id) {
        Optional<DatasetVersion> existing = repo.findByIdAndDeletedFalse(id);
        if (existing.isEmpty() || !authContext.canAccessOwner(effectiveOwner(existing.get()))) {
            return ApiResponse.fail("not found or no permission: " + id);
        }
        DatasetVersion version = existing.get();
        DatasetAsset asset = assetRepo.findByIdAndDeletedFalse(version.getAssetId()).orElse(null);
        if (asset == null) {
            log.warn("Reject dataset version delete because parent asset is missing or deleted: id={}, assetId={}", id, version.getAssetId());
            return ApiResponse.fail("dataset version parent asset not found or deleted: " + version.getAssetId());
        }
        Integer ownerUserId = version.getOwnerUserId() != null ? version.getOwnerUserId() : asset.getOwnerUserId();
        if (id.equals(asset.getCurrentVersionId())) {
            log.warn("Reject dataset version delete because it is current version: id={}", id);
            return ApiResponse.fail("current dataset version cannot be deleted");
        }
        if (trainingRepo.countByDatasetVersionId(id) > 0) {
            log.warn("Reject dataset version delete because it is referenced by training experiments: id={}", id);
            return ApiResponse.fail("dataset version is referenced by training experiments");
        }
        boolean minioDeleteQueued = false;
        String objectName = version.getStoragePath();
        boolean storageShared = objectName != null
                && !objectName.isBlank()
                && repo.existsByStoragePathAndDeletedFalseAndIdNot(objectName, id);
        if (objectName != null && !objectName.isBlank() && !storageShared) {
            try {
                authContext.requireObjectAccess(objectName, ownerUserId, "object not found or no permission");
                minioDeleteTaskService.enqueueDefaultBucketDelete(
                        objectName,
                        MinioDeleteTaskService.SOURCE_DATASET_VERSION,
                        id,
                        ownerUserId
                );
                minioDeleteQueued = true;
            } catch (Exception e) {
                log.warn("Reject dataset version delete because MinIO delete task cannot be queued: id={}, error={}", id, e.getMessage());
                return ApiResponse.fail("创建数据集版本文件删除任务失败: " + e.getMessage());
            }
        }

        Instant now = Instant.now();
        version.setDeleted(true);
        version.setDeletedAt(now);
        repo.save(version);
        log.info(
                "Dataset version soft deleted: id={}, assetId={}, minioDeleteQueued={}, ownerUserId={}",
                id,
                version.getAssetId(),
                minioDeleteQueued,
                ownerUserId
        );

        Map<String, Object> result = new HashMap<>();
        result.put("id", id);
        result.put("assetId", version.getAssetId());
        result.put("deleted", true);
        result.put("minioDeleteQueued", minioDeleteQueued);
        return ApiResponse.ok(result);
    }

    private boolean isWorkspaceDraft(DatasetVersion version) {
        if (!STATUS_DRAFT.equals(version.getStatus())
                || version.getParentVersionId() == null
                || version.getParentVersionId().isBlank()
                || version.getStoragePath() == null
                || version.getStoragePath().isBlank()) {
            return false;
        }
        return repo.findById(version.getParentVersionId())
                .map(parent -> Objects.equals(parent.getAssetId(), version.getAssetId())
                        && Objects.equals(parent.getStoragePath(), version.getStoragePath()))
                .orElse(false);
    }

    private Integer resolveAssetOwner(String assetId) {
        if (assetId == null || assetId.isBlank()) {
            return null;
        }
        return assetRepo.findByIdAndDeletedFalse(assetId).map(DatasetAsset::getOwnerUserId).orElse(null);
    }

    private Integer effectiveOwner(DatasetVersion version) {
        if (version.getOwnerUserId() != null) {
            return version.getOwnerUserId();
        }
        return resolveAssetOwner(version.getAssetId());
    }

    private boolean hasStorageMetadata(DatasetVersion body) {
        return body.getStoragePath() != null
                || body.getFileName() != null
                || body.getSizeBytes() != null;
    }

    private boolean hasCompleteStorageMetadata(DatasetVersion body) {
        return body.getStoragePath() != null && !body.getStoragePath().isBlank()
                && body.getFileName() != null && !body.getFileName().isBlank()
                && body.getSizeBytes() != null;
    }

    private String versionLabel(DatasetVersion body) {
        if (body.getVersionLabel() != null && !body.getVersionLabel().isBlank()) {
            return body.getVersionLabel().trim();
        }
        return body.getVersion() == null || body.getVersion().isBlank() ? null : body.getVersion().trim();
    }

    private String normalizeVersionStatus(String status) {
        if (status == null || status.isBlank()) {
            throw new IllegalArgumentException("status cannot be empty");
        }
        String normalized = status.trim().toUpperCase(Locale.ROOT);
        if (!STATUS_DRAFT.equals(normalized)
                && !STATUS_READY.equals(normalized)
                && !STATUS_DEPRECATED.equals(normalized)
                && !STATUS_ARCHIVED.equals(normalized)) {
            throw new IllegalArgumentException("status only supports DRAFT, READY, DEPRECATED, ARCHIVED");
        }
        return normalized;
    }

    private String normalizeStatusTransition(String status) {
        String normalized = normalizeVersionStatus(status);
        if (STATUS_DRAFT.equals(normalized)) {
            throw new IllegalArgumentException("status only supports READY, DEPRECATED, ARCHIVED");
        }
        return normalized;
    }

    private String activeDraftMessage(DatasetVersion activeDraft) {
        String id = activeDraft.getId();
        if (id == null || id.isBlank()) {
            return "dataset asset already has an active DRAFT version";
        }
        return "dataset asset already has an active DRAFT version: " + id;
    }

    private boolean isOneActiveDraftViolation(Throwable exception) {
        Throwable current = exception;
        while (current != null) {
            if (current instanceof org.hibernate.exception.ConstraintViolationException constraint
                    && "uk_dataset_version_one_active_draft".equalsIgnoreCase(constraint.getConstraintName())) {
                return true;
            }
            String message = current.getMessage();
            if (message != null
                    && message.toLowerCase(Locale.ROOT)
                            .contains("uk_dataset_version_one_active_draft")) {
                return true;
            }
            current = current.getCause();
        }
        return false;
    }

    private boolean storageMetadataChanged(DatasetVersion existing, DatasetVersion body) {
        return (body.getStoragePath() != null && !body.getStoragePath().equals(existing.getStoragePath()))
                || (body.getFileName() != null && !body.getFileName().equals(existing.getFileName()))
                || (body.getSizeBytes() != null && !body.getSizeBytes().equals(existing.getSizeBytes()));
    }
}

