package com.tss.platform.controller;

import com.tss.platform.dto.ApiResponse;
import com.tss.platform.entity.ModelAsset;
import com.tss.platform.entity.ModelVersion;
import com.tss.platform.repository.ModelAssetRepository;
import com.tss.platform.repository.ModelVersionRepository;
import com.tss.platform.security.AuthContext;
import com.tss.platform.service.MinioService;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import java.time.Instant;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;

@RestController
@RequestMapping("/api/model-versions")
public class ModelVersionCrudController {

    private final ModelVersionRepository repo;
    private final ModelAssetRepository assetRepo;
    private final MinioService minioService;
    private final AuthContext authContext;

    public ModelVersionCrudController(
            ModelVersionRepository repo,
            ModelAssetRepository assetRepo,
            MinioService minioService,
            AuthContext authContext
    ) {
        this.repo = repo;
        this.assetRepo = assetRepo;
        this.minioService = minioService;
        this.authContext = authContext;
    }

    @PostMapping
    public ApiResponse<ModelVersion> create(@RequestBody ModelVersion body) {
        if (body.getId() == null || body.getId().isBlank()) {
            body.setId("model-ver-" + UUID.randomUUID().toString().replace("-", ""));
        }
        Integer ownerUserId = resolveAssetOwner(body.getAssetId());
        if (!authContext.canAccessOwner(ownerUserId)) {
            return ApiResponse.fail("no permission for asset: " + body.getAssetId());
        }
        if (!authContext.isAdmin() && hasStorageMetadata(body)) {
            return ApiResponse.fail("storage metadata can only be generated by upload service");
        }
        body.setOwnerUserId(ownerUserId != null ? ownerUserId : authContext.currentUserId());
        if (body.getCreatedAt() == null) {
            body.setCreatedAt(Instant.now());
        }
        return ApiResponse.ok(repo.save(body));
    }

    @GetMapping("/{id}")
    public ApiResponse<ModelVersion> get(@PathVariable String id) {
        Optional<ModelVersion> v = repo.findById(id);
        if (v.isEmpty() || !authContext.canAccessOwner(effectiveOwner(v.get()))) {
            return ApiResponse.fail("not found or no permission: " + id);
        }
        return ApiResponse.ok(v.get());
    }

    @GetMapping
    public ApiResponse<List<ModelVersion>> list(@RequestParam(value = "assetId", required = false) String assetId) {
        if (assetId != null && !assetId.isBlank()) {
            if (authContext.isAdmin()) {
                return ApiResponse.ok(repo.findByAssetId(assetId));
            }
            return ApiResponse.ok(repo.findByAssetIdAndOwnerUserId(assetId, authContext.currentUserId()));
        }
        if (authContext.isAdmin()) {
            return ApiResponse.ok(repo.findAll());
        }
        return ApiResponse.ok(repo.findByOwnerUserId(authContext.currentUserId()));
    }

    @PutMapping("/{id}")
    public ApiResponse<ModelVersion> update(@PathVariable String id, @RequestBody ModelVersion body) {
        Optional<ModelVersion> existing = repo.findById(id);
        if (existing.isEmpty()) {
            return ApiResponse.fail("未找到: " + id);
        }
        ModelVersion e = existing.get();
        if (!authContext.canAccessOwner(effectiveOwner(e))) {
            return ApiResponse.fail("no permission: " + id);
        }
        String targetAssetId = body.getAssetId() == null || body.getAssetId().isBlank()
                ? e.getAssetId()
                : body.getAssetId();
        if (!authContext.isAdmin() && !Objects.equals(targetAssetId, e.getAssetId())) {
            return ApiResponse.fail("assetId cannot be modified");
        }
        if (!authContext.isAdmin() && storageMetadataChanged(e, body)) {
            return ApiResponse.fail("storage metadata cannot be modified");
        }
        Integer ownerUserId = resolveAssetOwner(targetAssetId);
        if (!authContext.canAccessOwner(ownerUserId)) {
            return ApiResponse.fail("no permission for asset: " + targetAssetId);
        }
        e.setAssetId(targetAssetId);
        e.setVersion(body.getVersion());
        if (authContext.isAdmin()) {
            e.setFileName(body.getFileName());
            e.setStoragePath(body.getStoragePath());
            e.setSizeBytes(body.getSizeBytes());
        }
        e.setOwnerUserId(ownerUserId != null ? ownerUserId : e.getOwnerUserId());
        return ApiResponse.ok(repo.save(e));
    }

    @DeleteMapping("/{id}")
    @Transactional
    public ApiResponse<Map<String, Object>> delete(@PathVariable String id) {
        Optional<ModelVersion> existing = repo.findById(id);
        if (existing.isEmpty() || !authContext.canAccessOwner(effectiveOwner(existing.get()))) {
            return ApiResponse.fail("not found or no permission: " + id);
        }
        ModelVersion version = existing.get();
        boolean deletedObject = false;
        String objectName = version.getStoragePath();
        if (objectName != null && !objectName.isBlank()) {
            try {
                authContext.requireObjectAccess(objectName, effectiveOwner(version), "object not found or no permission");
                minioService.deleteObject(objectName);
                deletedObject = true;
            } catch (Exception e) {
                return ApiResponse.fail("删除模型版本文件失败: " + e.getMessage());
            }
        }

        repo.delete(version);

        Map<String, Object> result = new HashMap<>();
        result.put("id", id);
        result.put("assetId", version.getAssetId());
        result.put("deletedObject", deletedObject);
        return ApiResponse.ok(result);
    }

    private Integer resolveAssetOwner(String assetId) {
        if (assetId == null || assetId.isBlank()) {
            return null;
        }
        return assetRepo.findById(assetId).map(ModelAsset::getOwnerUserId).orElse(null);
    }

    private Integer effectiveOwner(ModelVersion version) {
        if (version.getOwnerUserId() != null) {
            return version.getOwnerUserId();
        }
        return resolveAssetOwner(version.getAssetId());
    }

    private boolean hasStorageMetadata(ModelVersion body) {
        return body.getStoragePath() != null
                || body.getFileName() != null
                || body.getSizeBytes() != null;
    }

    private boolean storageMetadataChanged(ModelVersion existing, ModelVersion body) {
        return (body.getStoragePath() != null && !body.getStoragePath().equals(existing.getStoragePath()))
                || (body.getFileName() != null && !body.getFileName().equals(existing.getFileName()))
                || (body.getSizeBytes() != null && !body.getSizeBytes().equals(existing.getSizeBytes()));
    }
}

