package com.tss.platform.controller;

import com.tss.platform.dto.ApiResponse;
import com.tss.platform.entity.ModelAsset;
import com.tss.platform.entity.ModelVersion;
import com.tss.platform.repository.ModelAssetRepository;
import com.tss.platform.repository.ModelVersionRepository;
import com.tss.platform.repository.TrainingExperimentVersionRepository;
import com.tss.platform.security.AuthContext;
import com.tss.platform.service.MinioDeleteTaskService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import java.time.Instant;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/api/model-versions")
public class ModelVersionCrudController {

    private static final Logger log = LoggerFactory.getLogger(ModelVersionCrudController.class);

    private final ModelVersionRepository repo;
    private final ModelAssetRepository assetRepo;
    private final TrainingExperimentVersionRepository trainingRepo;
    private final MinioDeleteTaskService minioDeleteTaskService;
    private final AuthContext authContext;

    public ModelVersionCrudController(
            ModelVersionRepository repo,
            ModelAssetRepository assetRepo,
            TrainingExperimentVersionRepository trainingRepo,
            MinioDeleteTaskService minioDeleteTaskService,
            AuthContext authContext
    ) {
        this.repo = repo;
        this.assetRepo = assetRepo;
        this.trainingRepo = trainingRepo;
        this.minioDeleteTaskService = minioDeleteTaskService;
        this.authContext = authContext;
    }

    @PostMapping
    public ApiResponse<ModelVersion> create(@RequestBody ModelVersion body) {
        if (body.getAssetId() == null || body.getAssetId().isBlank()) {
            return ApiResponse.fail("assetId cannot be empty");
        }
        if (body.getVersion() == null || body.getVersion().isBlank()) {
            return ApiResponse.fail("version cannot be empty");
        }
        body.setAssetId(body.getAssetId().trim());
        body.setVersion(body.getVersion().trim());
        body.setId("model-ver-" + UUID.randomUUID().toString().replace("-", ""));
        Integer ownerUserId = resolveAssetOwner(body.getAssetId());
        if (!authContext.canAccessOwner(ownerUserId)) {
            return ApiResponse.fail("no permission for asset: " + body.getAssetId());
        }
        if (!authContext.isAdmin() && hasStorageMetadata(body)) {
            return ApiResponse.fail("storage metadata can only be generated by upload service");
        }
        if (repo.existsByAssetIdAndVersion(body.getAssetId(), body.getVersion())) {
            return ApiResponse.fail("model version already exists for asset: " + body.getAssetId());
        }
        body.setOwnerUserId(ownerUserId != null ? ownerUserId : authContext.currentUserId());
        if (body.getCreatedAt() == null) {
            body.setCreatedAt(Instant.now());
        }
        body.setDeleted(false);
        body.setDeletedAt(null);
        return ApiResponse.ok(repo.save(body));
    }

    @GetMapping("/{id}")
    public ApiResponse<ModelVersion> get(@PathVariable String id) {
        Optional<ModelVersion> v = repo.findByIdAndDeletedFalse(id);
        if (v.isEmpty() || !authContext.canAccessOwner(effectiveOwner(v.get()))) {
            return ApiResponse.fail("not found or no permission: " + id);
        }
        return ApiResponse.ok(v.get());
    }

    @GetMapping
    public ApiResponse<List<ModelVersion>> list(@RequestParam(value = "assetId", required = false) String assetId) {
        if (assetId != null && !assetId.isBlank()) {
            if (authContext.isAdmin()) {
                return ApiResponse.ok(repo.findByAssetIdAndDeletedFalse(assetId));
            }
            if (!authContext.canAccessOwner(resolveAssetOwner(assetId))) {
                return ApiResponse.fail("not found or no permission: " + assetId);
            }
            return ApiResponse.ok(repo.findByAssetIdAndDeletedFalse(assetId));
        }
        if (authContext.isAdmin()) {
            return ApiResponse.ok(repo.findByDeletedFalse());
        }
        Set<String> assetIds = assetRepo.findByOwnerUserIdAndDeletedFalse(authContext.currentUserId())
                .stream()
                .map(ModelAsset::getId)
                .filter(id -> id != null && !id.isBlank())
                .collect(Collectors.toSet());
        return ApiResponse.ok(assetIds.isEmpty() ? List.of() : repo.findByAssetIdInAndDeletedFalse(assetIds));
    }

    @PutMapping("/{id}")
    public ApiResponse<ModelVersion> update(@PathVariable String id, @RequestBody ModelVersion body) {
        Optional<ModelVersion> existing = repo.findByIdAndDeletedFalse(id);
        if (existing.isEmpty()) {
            return ApiResponse.fail("未找到: " + id);
        }
        ModelVersion e = existing.get();
        if (!authContext.canAccessOwner(effectiveOwner(e))) {
            return ApiResponse.fail("no permission: " + id);
        }
        String targetAssetId = body.getAssetId() == null || body.getAssetId().isBlank()
                ? e.getAssetId()
                : body.getAssetId().trim();
        if (body.getVersion() == null || body.getVersion().isBlank()) {
            return ApiResponse.fail("version cannot be empty");
        }
        String targetVersion = body.getVersion().trim();
        if (!authContext.isAdmin() && !Objects.equals(targetAssetId, e.getAssetId())) {
            return ApiResponse.fail("assetId cannot be modified");
        }
        if (!authContext.isAdmin() && storageMetadataChanged(e, body)) {
            return ApiResponse.fail("storage metadata cannot be modified");
        }
        Integer ownerUserId = resolveAssetOwner(targetAssetId);
        if (!authContext.canAccessOwner(ownerUserId)) {
            return ApiResponse.fail("no permission for asset: " + targetAssetId);
        }
        if (repo.existsByAssetIdAndVersionAndIdNot(targetAssetId, targetVersion, id)) {
            return ApiResponse.fail("model version already exists for asset: " + targetAssetId);
        }
        e.setAssetId(targetAssetId);
        e.setVersion(targetVersion);
        if (authContext.isAdmin()) {
            e.setFileName(body.getFileName());
            e.setStoragePath(body.getStoragePath());
            e.setSizeBytes(body.getSizeBytes());
        }
        e.setOwnerUserId(ownerUserId != null ? ownerUserId : e.getOwnerUserId());
        return ApiResponse.ok(repo.save(e));
    }

    @DeleteMapping("/{id}")
    @Transactional
    public ApiResponse<Map<String, Object>> delete(@PathVariable String id) {
        Optional<ModelVersion> existing = repo.findByIdAndDeletedFalse(id);
        if (existing.isEmpty() || !authContext.canAccessOwner(effectiveOwner(existing.get()))) {
            return ApiResponse.fail("not found or no permission: " + id);
        }
        ModelVersion version = existing.get();
        ModelAsset asset = assetRepo.findByIdAndDeletedFalse(version.getAssetId()).orElse(null);
        if (asset == null) {
            log.warn("Reject model version delete because parent asset is missing or deleted: id={}, assetId={}", id, version.getAssetId());
            return ApiResponse.fail("model version parent asset not found or deleted: " + version.getAssetId());
        }
        Integer ownerUserId = version.getOwnerUserId() != null ? version.getOwnerUserId() : asset.getOwnerUserId();
        if (trainingRepo.countByModelVersionId(id) > 0) {
            log.warn("Reject model version delete because it is referenced by training experiments: id={}", id);
            return ApiResponse.fail("model version is referenced by training experiments");
        }
        boolean minioDeleteQueued = false;
        String objectName = version.getStoragePath();
        if (objectName != null && !objectName.isBlank()) {
            try {
                authContext.requireObjectAccess(objectName, ownerUserId, "object not found or no permission");
                minioDeleteTaskService.enqueueDefaultBucketDelete(
                        objectName,
                        MinioDeleteTaskService.SOURCE_MODEL_VERSION,
                        id,
                        ownerUserId
                );
                minioDeleteQueued = true;
            } catch (Exception e) {
                log.warn("Reject model version delete because MinIO delete task cannot be queued: id={}, error={}", id, e.getMessage());
                return ApiResponse.fail("创建模型版本文件删除任务失败: " + e.getMessage());
            }
        }

        Instant now = Instant.now();
        version.setDeleted(true);
        version.setDeletedAt(now);
        repo.save(version);
        log.info(
                "Model version soft deleted: id={}, assetId={}, minioDeleteQueued={}, ownerUserId={}",
                id,
                version.getAssetId(),
                minioDeleteQueued,
                ownerUserId
        );

        Map<String, Object> result = new HashMap<>();
        result.put("id", id);
        result.put("assetId", version.getAssetId());
        result.put("deleted", true);
        result.put("minioDeleteQueued", minioDeleteQueued);
        return ApiResponse.ok(result);
    }

    private Integer resolveAssetOwner(String assetId) {
        if (assetId == null || assetId.isBlank()) {
            return null;
        }
        return assetRepo.findByIdAndDeletedFalse(assetId).map(ModelAsset::getOwnerUserId).orElse(null);
    }

    private Integer effectiveOwner(ModelVersion version) {
        if (version.getOwnerUserId() != null) {
            return version.getOwnerUserId();
        }
        return resolveAssetOwner(version.getAssetId());
    }

    private boolean hasStorageMetadata(ModelVersion body) {
        return body.getStoragePath() != null
                || body.getFileName() != null
                || body.getSizeBytes() != null;
    }

    private boolean storageMetadataChanged(ModelVersion existing, ModelVersion body) {
        return (body.getStoragePath() != null && !body.getStoragePath().equals(existing.getStoragePath()))
                || (body.getFileName() != null && !body.getFileName().equals(existing.getFileName()))
                || (body.getSizeBytes() != null && !body.getSizeBytes().equals(existing.getSizeBytes()));
    }
}

