apiVersion: v1
kind: Namespace
metadata:
  name: tss-training
  labels:
    app.kubernetes.io/part-of: tss-platform
    tss.ai/workload-type: training
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
