name: 前端自动化部署

on:
  push:
    branches:
      - frontend-demo1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置 Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 安装依赖
        run: npm install

      - name: 打包项目
        run: npm run build

      - name: 上传 dist 到服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SECONDARY_SERVER_HOST }}
          username: ${{ secrets.SECONDARY_SERVER_USER }}
          password: ${{ secrets.SECONDARY_SERVER_PASSWORD }}
          source: "dist/*"        # 上传 dist 里面所有内容
          target: "/var/www/"  # 标准路径！
          strip_components: 1    # 自动去掉 dist 目录层级